language: python
python:
  -  3.5
install:
  - pip install mkdocs
  - pip install mkdocs-material
  - pip install pymdown-extensions
script:
  - mkdocs build --clean
after_success:  |
  if [ -n "$GITHUB_API_KEY" ]; then
    cd "$TRAVIS_BUILD_DIR"
    cd site
    git init
    git add .
    git -c user.name=$GITHUB_NAME -c user.email=$GITHUB_EMAIL commit -m "Auto Deployment"
    git push -f -q https://$GITHUB_NAME:$GITHUB_API_KEY@github.com/westwind/westwind.github.io master
    cd "$TRAVIS_BUILD_DIR"
  fi
